dataset: 3285
train_version: v7
gpu: 0
# 'EfficientNetB0', 'B1', 'B2', 'B3', 'B4','B5', 'B6', 'B7'
# 'resnet50','resnet50V2','resnet101','resnet101V2','resnet152','resnet152V2','InceptionResNetV2'
model_name: InceptionV3
batch: 32
optimizer: Adam
epoch: 40
es_patience: 15
reduce_lr_factor: 0.2
initial_learning_rate: 1.0e-03
reduce_lr_patience: 3
learning_rate_scheduler: ReduceLROnPlateau #[ReduceLROnPlateau, CosineDecay]